media:
  input: static/images
  output: /images

content:
  - name: posts
    label: 글
    type: collection
    path: content
    filename:
      template: "{primary}.md"
      field: true
    subfolders: true
    view:
      fields: [title, date, categories]
      primary: title
      sort: [date, title]
      default:
        sort: date
        order: desc

    fields:
      - name: title
        label: 제목
        type: string
        required: true
    
      - name: date
        label: 날짜
        type: date
        required: true
        options:
          time: true
          format: "yyyy-MM-dd'T'HH:mm:ssxxx"
    
      - name: categories
        label: 카테고리
        type: string
        list: true
        default:
          - 일기
    
      - name: draft
        label: 초안
        type: boolean
        default: true
    
      - name: build
        label: 빌드 설정
        type: object
        fields:
          - name: list
            label: 목록 표시
            type: select
            default: never
            options:
              values:
                - never
                - always
    
      - name: body
        label: 본문
        type: rich-text